version: "3.0"

services:
  # FastAPI
  api:
    container_name: "api"
    build: .
    restart: always
    tty: true
    ports:
      - 8005:8000
    env_file:
      - .env
    volumes:
      - .:/app
