name: Test CI

on: push
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout current branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: create firebase service account file
        run: echo -n "{{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 -d > ./app/service_account.json
      - uses: akhileshns/heroku-deploy@v3.9.9 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP }} #Must be unique in Heroku
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
